version: "3"
services:
  myapp1:
    build:
      context: .
      dockerfile: Dockerfile-app1
    container_name: myapp1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - myactivemq
  myapp2:
    build:
      context: .
      dockerfile: Dockerfile-app2
    container_name: myapp2
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - myactivemq
  myactivemq:
    image: rmohr/activemq:5.15.9
    container_name: myactivemq
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"