version: "3"
services:
  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - myactivemq
  myactivemq:
    image: rmohr/activemq:5.15.9
    container_name: myactivemq
    restart: always
    ports:
      - "8161:8161"
      - "61616:61616"